spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pkdg
    username: pkdg
    password: pkdg
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
