services:
  postgresql:
    image: postgres:14.2
    environment:
      POSTGRES_USER: pkdg
      POSTGRES_PASSWORD: pkdg
      POSTGRES_DB: pkdg
      PGDATA: /data/postgres
    volumes:
      - pkdg-postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

volumes:
  pkdg-postgres:

